### PR TITLE
Nizar

### PR DESCRIPTION
**Pull request by Nkury**
Added Level C- level that teaches and incorporates GUILT.

### CODE REVIEW

**Comment by alexgryan** [comment]
@Nkury I need you to update your files. You might have not received some more recent files from master and it is creating a conflict.

**Comment by Nkury** [comment]
I merged it with master. Yeah, my bad for not updating it throughout all those master changes

**Comment by Nkury** [comment]
There we go. I'll let you review the pull request now

**Comment by alexgryan** [comment]
@Nkury Ty Nizar-kun. Merge request granted.

**Pull request merged**
