### PR TITLE
The best branch

### PR DESCRIPTION
**Pull request by Renigma**
Jeremy 'The Best' Johnson:

added projectile arc. commented on future opportunities created

### CODE REVIEW

**Comment by skinnyMan** [comment]
@alexgryan I can take at this one, it appears to be in conflict.

**Comment by skinnyMan** [comment]
@Renigma I've merged the master into your branch, can you verify that nothing you worked on broke?

**Comment by alexgryan** [comment]
@skinnyMan Thanks Angel! I appreciate it! @Renigma please respond so we can verify!

**Comment by Renigma** [comment]
There did not but it may be that one of my eariler edits were from an older version and such that the rest of the codenmay be as well.

**Comment by Renigma** [comment]
If there is still issue I can redo the code over spring in a new branch

**Comment by alexgryan** [comment]
@Renigma so it works to your satisfaction?

**Comment by Renigma** [comment]
@alexgryan ill have to test it again, but the variables should definitly be tweaked and playtested; the inital &final gravity, and the lob max

**Comment by skinnyMan** [comment]
@Renigma , were you able to test this? we should close this one soon.

**Comment by Renigma** [comment]
It worked on the version I had like in class but I should try updating the
version

**Pull request merged**
